here::here("path", "to", "file")
library(rrtools)
##rrtools::create_compendium("~/Desktop/EcohealthTest")
##usethis::use_git()
##usethis::use_mit_license()
##options(usethis.full_name = "alex schiller")
##usethis::use_mit_license()
##rrtools::use_readme_rmd()
usethis::use_github(protocol = "https")
rrtools::use_analysis()
library(dplyr)
library(readr)
library(ggplot2)
library(ggthemes)
library(citr)
rrtools::add_dependencies_to_description()
sessionInfo()
